[package]
name = "cirque-parser"
version = "0.1.0"
license = "MIT"
edition = "2024"

[dependencies]
bytes = "1.7.1"
lending-iterator = "0.1.7"
log = "0.4.22"
nom = "7.1.3"
slice-ring-buffer = "0.3.4"
smallvec = "1.13.2"

[lints]
workspace = true
